name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Angular app
        working-directory: cosmicexperience-frontend
        run: |
          docker build -t angular-app .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-registry/angular-app

      - name: Build and push Nest.js app
        working-directory: cosmicexperience-backend
        run: |
          docker build -t nest-app .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-registry/nest-app
